### ISSUE TITLE
dialog files duplicated and keys translated

### ISSUE THREAD

**Issue by atd** [OpenVoiceOS/skill-ovos-weather#22]
`dialog` files seem to be duplicated. For instance: https://github.com/OpenVoiceOS/skill-ovos-weather/blob/dev/locale/es-es/current-weather-local.dialog and https://github.com/OpenVoiceOS/skill-ovos-weather/blob/dev/locale/es-es/dialog/current/current-weather-local.dialog (but also in `en-us`) This makes the skill randomly fail, since the keys are different. Any thoughts on how this wants to be? Shouldn't translated `.dialog` files be moved to their original folders? or previous ones removed

On the other hand, keys are translated. So `{condición}` in Spanish is not a valid key. Maybe the translation script can be fixed to avoid translating keys?

**Comment by emphasize** [comment]
Fixed with https://github.com/OpenVoiceOS/skill-ovos-weather/commit/e2add03b2b91b4fdbadf7196a30a94156a382c55
