### ISSUE TITLE
Weather from different areas

### ISSUE THREAD

**Issue by builderjer** [OpenVoiceOS/skill-ovos-weather#24]
When asking for weather, 'hey mycroft, what is the weather' it works just fine

If I ask 'hey mycroft, what is the weather in Paris', it fails with "weather reports are unavailable.  I does this with any inquiry with a different location

**Comment by emphasize** [comment]
most likely due to #30

**Comment by emphasize** [comment]
can we close?

**Comment by builderjer** [comment]
I know this is fixed in ovos, I willopen another with neon
