### ISSUE TITLE
Issue with weather in Italian

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/skill-ovos-weather#53]
when I ask the temperature in italian: ``che tempo fa?`` I get for example: ``Attualmente è nuvoloso e 25.2 gradi centigradi`` the issue is with the number: ``25.2`` is read as ``252`` instead of "25 gradi e 2``.
A suggestion to simplify temperature reading would be a 0.5 approximation, in order to have "25 gradi" or "26 gradi" and maybe, have a new command ``qual'è la temperatura precisa``, in English: ``what is the precise temperature`` to skip the approximation.

**Comment by emphasize** [comment]
I don't think this is a skill issue. What is converting `25.2` into `252` ?

**Comment by denics** [comment]
then the issue should be raised to core, @JarbasAl do you get the same with Portuguese?

**Comment by emphasize** [comment]
I'm not quite clear about the problem.
does it voice out https://translate.google.de/?sl=de&tl=it&text=es%20ist%20252%20grad&op=translate
instead of https://translate.google.de/?sl=de&tl=it&text=es%20ist%2025.2%20grad&op=translate

**Comment by denics** [comment]
The issue is how the number is read. In the logs the answer is correct: 25.2, but then it is spell as 252. I am testing on ``ovos-docker``, with this configuration:
```json
{
  "lang": "it-it",
  "tts": {
    "module": "ovos-tts-plugin-mimic3-server",
    "fallback_module": "",
    "ovos-tts-plugin-mimic3-server": {
        "voice": "it_IT/mls_low"
    }
  },
  "stt": {
    "module": "ovos-stt-plugin-server",
    "fallback_module": "ovos-stt-plugin-vosk",
    "ovos-stt-plugin-vosk": {
        "model": "https://alphacephei.com/vosk/models/vosk-model-small-it-0.22.zip"
    }
  }
}
```

**Comment by emphasize** [comment]
so, it's ultimately a mimic3-it synth issue

**Comment by JarbasAl** [comment]
seems you need to change TTS then, mimic3 wont be getting more updates....

**Comment by denics** [comment]
Ok, I'll test with piper. Should I open a new issue for documenting this on the mimic3 repo?

**Comment by JarbasAl** [comment]
> Ok, I'll test with piper. Should I open a new issue for documenting this on the mimic3 repo?

this would be model/voice specific, any issues should go into the original mycroft mimic3 repo, but don't expect any answers in there either other than maybe someone telling you to move to piper

i'd recommend just using piper which has all the same mimic3 voices, and then open issues in piper repo if needed, I'm sure Piper wants (and gives you) feedback and is actively improving the voices!
